# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :build do
    gym(scheme: "FastlaneActions",
       configuration: "Debug",
       clean: true,
       export_method: "development"
    )
  end

  lane :bump_version do
    increment_build_number
    increment_version_number
    clean_build_artifacts
    commit_version_bump(xcodeproj: "./FastlaneActions.xcodeproj", force: true)
    push_to_git_remote
  end

  lane :beta_badge do
    add_badge(shield: "Version-#{lane_context[SharedValues::VERSION_NUMBER]}-blue", dark: true)
  end

  lane :tag do 
    add_git_tag(prefix: "v",
                postfix: "-RC1",
                build_number: "1.0.0"
    		)
    push_git_tags
  end
end
